//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gender
    {
        public Gender()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
