//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public Hotel()
        {
            this.TourGroupHotels = new HashSet<TourGroupHotel>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string status { get; set; }
        public int destination_id { get; set; }
        public Nullable<double> price { get; set; }
    
        public virtual Destination Destination { get; set; }
        public virtual ICollection<TourGroupHotel> TourGroupHotels { get; set; }
    }
}
