//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourSite
    {
        public TourSite()
        {
            this.Tours = new HashSet<Tour>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int destination_id { get; set; }
    
        public virtual Destination Destination { get; set; }
        public virtual ICollection<Tour> Tours { get; set; }
    }
}
