//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        public Tour()
        {
            this.TourGroups = new HashSet<TourGroup>();
            this.TourSites = new HashSet<TourSite>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int category_id { get; set; }
        public int tour_price_id { get; set; }
        public int destination_id { get; set; }
    
        public virtual Destination Destination { get; set; }
        public virtual TourCategory TourCategory { get; set; }
        public virtual TourPrice TourPrice { get; set; }
        public virtual ICollection<TourGroup> TourGroups { get; set; }
        public virtual ICollection<TourSite> TourSites { get; set; }
    }
}
