//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourGroup
    {
        public TourGroup()
        {
            this.TransportsTourGroups = new HashSet<TransportsTourGroup>();
            this.Employees = new HashSet<Employee>();
            this.Customers = new HashSet<Customer>();
        }
    
        public int id { get; set; }
        public int tour_id { get; set; }
        public string name { get; set; }
        public System.DateTime depart_date { get; set; }
        public System.DateTime return_date { get; set; }
    
        public virtual Tour Tour { get; set; }
        public virtual TourGroupFee TourGroupFee { get; set; }
        public virtual TourGroupHotel TourGroupHotel { get; set; }
        public virtual ICollection<TransportsTourGroup> TransportsTourGroups { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
