//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourGroupFee
    {
        public int Id { get; set; }
        public int tourgroup_id { get; set; }
        public double hotel_fee { get; set; }
        public double transport_fee { get; set; }
    
        public virtual TourGroup TourGroup { get; set; }
    }
}
